runtime: go
api_version: go1

handlers:
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico
- url: /static
  static_dir: static
- url: /.*
  script: _go_app
- url: /_ah/remote_api
  script: _go_app

automatic_scaling:
  max_idle_instances: 1
